# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  ORDER_SERVICE_URL: "http://order-service:8000"
  INVENTORY_SERVICE_URL: "http://inventory-service:8000"
  PAYMENT_SERVICE_URL: "http://payment-service:8000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB_ORDERS: "orders"
  POSTGRES_DB_INVENTORY: "inventory"
  POSTGRES_DB_PAYMENTS: "payments"
  PULSAR_HOST: "pulsar"
  PULSAR_PORT: "6650"
  PULSAR_ADMIN_PORT: "8080"
