# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)

